In [1]:
# Import dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from citipy import citipy

In [21]:
# Create set of 2000 random latitudes and longitudes
# Create combinations
lats = np.random.uniform(-90, 90, size=2000)
lngs = np.random.uniform(-180, 180, size=2000)
lats_lngs = zip(lats, lngs)

# Add combinations to a list
coordinates = list(lats_lngs)

In [22]:
# Get nearest city 
# Create list for holding cities
cities = []

# Identify nearest city
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    # If city is unique, add it to list
    if city not in cities:
        cities.append(city)
    
# Confirm sufficient count
len(cities)

719

In [35]:
# Perform API call
# Import requests module and api key
import requests
from config import weather_api_key as api_key

# Build base url
base_url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + api_key

# Create an empty list to hold the weather data
city_data = []

# Loop through all the cities in our list
for city in cities:
    # Create endpoint URL with each city
    city_url = base_url + "&q=" + city.replace(" ", "+")
    
    # Run an API request for each of the cities
    try:
        # Parse the JSON and retrieve data
        city_weather = requests.get(city_url).json()
        
        # Parse out the needed data
        city_country = city_country = city_weather['sys']['country']
        city_lat = city_weather['coord']['lat']
        city_lng = city_weather['coord']['lon']
        city_max_temp = city_weather['main']['temp_max']
        city_humidity = city_weather['main']['humidity']
        city_clouds = city_weather['clouds']['all']
        city_wind = city_weather['wind']['speed']
        city_weather_desc = city_weather['weather'][0]['description']

        # Append the city information into city_data list
        city_data.append({"City": city.title(),
                          "Country": city_country,
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Current Description": city_weather_desc})

    # If an error is experienced, skip the city
    except:
        pass

In [36]:
# Convert the array of dictionaries to a Pandas DataFrame
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Punta Arenas,CL,-53.1500,-70.9167,42.80,87,75,4.61,broken clouds
1,San Jeronimo,PE,-11.9472,-75.2829,46.69,81,69,2.35,broken clouds
2,Ternate,ID,0.8000,127.4000,83.64,74,81,11.14,broken clouds
3,Ormara,PK,25.2088,64.6357,82.51,66,70,10.83,broken clouds
4,Novikovo,RU,51.1537,37.8879,47.68,66,93,7.54,overcast clouds
5,Bredasdorp,ZA,-34.5322,20.0403,48.20,87,0,5.75,clear sky
6,Mataura,NZ,-46.1927,168.8643,57.99,64,51,7.00,broken clouds
7,Magadan,RU,59.5667,150.8000,31.66,98,100,4.09,light snow
8,New Norfolk,AU,-42.7826,147.0587,62.01,73,100,5.99,light rain
9,Puerto Ayora,EC,-0.7393,-90.3518,75.00,99,80,3.29,broken clouds

In [37]:
# Export DataFrame as csv file
# Create the output file (CSV)
output_data_file = 'Weather_Database/WeatherPy_Database.csv'

# Export the City_Data into a CSV
city_data_df.to_csv(output_data_file, index_label="City_ID")